// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import AdminHeader from "@/components/AdminHeader";
// import AdminFooter from "@/components/AdminFooter";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       ><AdminHeader/>
//         {children}
//         <AdminFooter/>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"

import "./globals.css"

import AdminHeader from "@/components/AdminHeader"
import AdminFooter from "@/components/AdminFooter"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: {
    default: "AEDSIndia Admin",
    template: "%s | AEDSIndia Admin",
  },

  description:
    "AEDSIndia administrative dashboard used by authorized employees to manage products, orders, inventory, performance leads, and support tickets.",

  keywords: [
    "AEDSIndia",
    "AEDSIndia Admin",
    "Admin Dashboard",
    "Inventory Management",
    "Orders Management",
    "Ecommerce Admin",
  ],

  authors: [
    { name: "AEDSIndia" }
  ],

  creator: "AEDSIndia",

  robots: {
    index: false,
    follow: false,
  },

  icons: {
    icon: "/logo.png",
  },

  openGraph: {
    title: "AEDSIndia Admin Dashboard",
    description:
      "Secure administrative dashboard for AEDSIndia internal operations.",
    siteName: "AEDSIndia Admin",
    type: "website",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (

<html lang="en">

<body
className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
>

<div className="min-h-screen flex flex-col">

{/* HEADER */}
<AdminHeader />


{/* MAIN CONTENT */}

<main className="flex-1 flex justify-center">

<div className="w-full max-w-7xl px-6 py-8">

{children}

</div>

</main>


{/* FOOTER */}

<AdminFooter />

</div>

</body>

</html>

  )
}